succeed message v3

diff --git a/.github/workflows/01-building-blocks.yaml b/.github/workflows/01-building-blocks.yaml
--- a/.github/workflows/01-building-blocks.yaml
+++ b/.github/workflows/01-building-blocks.yaml
@@ -15,8 +15,8 @@ jobs:
     steps:
       - name: succeed step
         run: |
-          echo "i will succeed"
-          exit 0
+          echo "i will fail"
+          exit 1
       - name: Say goodbye
         run: echo "goodbye"
 
